// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/sabiqazhar/clinic-monolith/internal/infrastructure/broker"
	"github.com/sabiqazhar/clinic-monolith/internal/infrastructure/cache"
	"github.com/sabiqazhar/clinic-monolith/internal/infrastructure/db"
	handler3 "github.com/sabiqazhar/clinic-monolith/internal/modules/appointment/handler"
	repository3 "github.com/sabiqazhar/clinic-monolith/internal/modules/appointment/repository"
	service3 "github.com/sabiqazhar/clinic-monolith/internal/modules/appointment/service"
	handler2 "github.com/sabiqazhar/clinic-monolith/internal/modules/billing/handler"
	repository2 "github.com/sabiqazhar/clinic-monolith/internal/modules/billing/repository"
	service2 "github.com/sabiqazhar/clinic-monolith/internal/modules/billing/service"
	"github.com/sabiqazhar/clinic-monolith/internal/modules/patient/handler"
	"github.com/sabiqazhar/clinic-monolith/internal/modules/patient/repository"
	"github.com/sabiqazhar/clinic-monolith/internal/modules/patient/service"
	"go.uber.org/zap"
	"time"
)

import (
	_ "github.com/go-sql-driver/mysql"
	_ "github.com/jackc/pgx/v5/stdlib"
	_ "net/http/pprof"
)

// Injectors from wire.go:

// InitializeApp is the INJECTOR FUNCTION.
// All config values are passed as parameters - Wire provides them from injector's args
func InitializeApp(pgDsn db.PGDsn, mySQLDsn db.MySQLDsn, redisAddr cache.RedisAddr, rabbitURL broker.RabbitURL, logger *zap.Logger) (*App, error) {
	pool, err := db.NewPostgresPool(pgDsn)
	if err != nil {
		return nil, err
	}
	patientRepository := repository.NewPatientRepo(pool, logger)
	redisCache, err := cache.NewRedisClient(redisAddr)
	if err != nil {
		return nil, err
	}
	mainCacheAdapter := newCacheAdapter(redisCache)
	rabbitMQ, err := broker.NewRabbitMQ(rabbitURL, logger)
	if err != nil {
		return nil, err
	}
	mainPublisherAdapter := newPublisherAdapter(rabbitMQ)
	patientService := service.NewPatientService(patientRepository, mainCacheAdapter, mainPublisherAdapter, logger)
	patientHandler := handler.NewPatientHandler(patientService, logger)
	invoiceRepository := repository2.NewBillingRepo(pool, logger)
	billingService := service2.NewBillingService(invoiceRepository, patientService, mainCacheAdapter, mainPublisherAdapter, logger)
	billingHandler := handler2.NewBillingHandler(billingService, logger)
	sqlDB, err := db.NewMySQLDB(mySQLDsn)
	if err != nil {
		return nil, err
	}
	appointmentRepository := repository3.NewAppointmentRepo(sqlDB, logger)
	appointmentService := service3.NewAppointmentService(appointmentRepository, patientService, mainCacheAdapter, mainPublisherAdapter, logger)
	appointmentHandler := handler3.NewAppointmentHandler(appointmentService, logger)
	app := &App{
		PatientHandler:     patientHandler,
		BillingHandler:     billingHandler,
		AppointmentHandler: appointmentHandler,
	}
	return app, nil
}

// wire.go:

type cacheAdapter struct{ *cache.RedisCache }

func (a *cacheAdapter) Get(ctx context.Context, key string) ([]byte, error) {
	return a.RedisCache.Get(ctx, key)
}

func (a *cacheAdapter) Set(ctx context.Context, key string, value []byte, ttl time.Duration) error {
	return a.RedisCache.Set(ctx, key, value, ttl)
}

type publisherAdapter struct{ *broker.RabbitMQ }

func (p *publisherAdapter) PublishEventAsync(ctx context.Context, topic string, payload []byte) {
	_ = p.RabbitMQ.Publish(ctx, topic, payload)
}

// App adalah struct yang menampung semua handler yang sudah dirakit.
// Wire akan mengisi field-field ini secara otomatis.
type App struct {
	PatientHandler     *handler.PatientHandler
	BillingHandler     *handler2.BillingHandler
	AppointmentHandler *handler3.AppointmentHandler
}

// Provider functions for adapters
func newCacheAdapter(redis *cache.RedisCache) *cacheAdapter {
	return &cacheAdapter{redis}
}

func newPublisherAdapter(rabbit *broker.RabbitMQ) *publisherAdapter {
	return &publisherAdapter{rabbit}
}
