// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"context"
)

type Querier interface {
	FindPatientByID(ctx context.Context, id string) (FindPatientByIDRow, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	InsertPatient(ctx context.Context, arg InsertPatientParams) error
}

var _ Querier = (*Queries)(nil)
