// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findPatientByID = `-- name: FindPatientByID :one
SELECT id, full_name, email, created_at 
FROM patients 
WHERE id = $1 AND deleted_at IS NULL
`

type FindPatientByIDRow struct {
	ID        string             `json:"id"`
	FullName  string             `json:"full_name"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindPatientByID(ctx context.Context, id string) (FindPatientByIDRow, error) {
	row := q.db.QueryRow(ctx, findPatientByID, id)
	var i FindPatientByIDRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (id, topic, payload, status, created_at) 
VALUES ($1, $2, $3, 'pending', NOW())
`

type InsertOutboxEventParams struct {
	ID      string `json:"id"`
	Topic   string `json:"topic"`
	Payload []byte `json:"payload"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent, arg.ID, arg.Topic, arg.Payload)
	return err
}

const insertPatient = `-- name: InsertPatient :exec
INSERT INTO patients (id, full_name, email, created_at) 
VALUES ($1, $2, $3, NOW())
`

type InsertPatientParams struct {
	ID       string `json:"id"`
	FullName string `json:"full_name"`
	Email    string `json:"email"`
}

func (q *Queries) InsertPatient(ctx context.Context, arg InsertPatientParams) error {
	_, err := q.db.Exec(ctx, insertPatient, arg.ID, arg.FullName, arg.Email)
	return err
}
