// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BillingInvoice struct {
	ID          string             `json:"id"`
	PatientID   string             `json:"patient_id"`
	Amount      pgtype.Numeric     `json:"amount"`
	Status      pgtype.Text        `json:"status"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type OutboxEvent struct {
	ID          string             `json:"id"`
	Topic       string             `json:"topic"`
	Payload     []byte             `json:"payload"`
	Status      pgtype.Text        `json:"status"`
	Attempts    pgtype.Int4        `json:"attempts"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type Patient struct {
	ID        string             `json:"id"`
	FullName  string             `json:"full_name"`
	Email     string             `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
