// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"context"
)

type Querier interface {
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) error
	GetInvoiceByID(ctx context.Context, id string) (GetInvoiceByIDRow, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
}

var _ Querier = (*Queries)(nil)
