// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :exec
INSERT INTO billing_invoices (id, patient_id, amount, status, description, created_at) 
VALUES ($1, $2, $3, $4, $5, NOW())
`

type CreateInvoiceParams struct {
	ID          string         `json:"id"`
	PatientID   string         `json:"patient_id"`
	Amount      pgtype.Numeric `json:"amount"`
	Status      pgtype.Text    `json:"status"`
	Description pgtype.Text    `json:"description"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) error {
	_, err := q.db.Exec(ctx, createInvoice,
		arg.ID,
		arg.PatientID,
		arg.Amount,
		arg.Status,
		arg.Description,
	)
	return err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, patient_id, amount, status, description, created_at 
FROM billing_invoices 
WHERE id = $1
`

type GetInvoiceByIDRow struct {
	ID          string             `json:"id"`
	PatientID   string             `json:"patient_id"`
	Amount      pgtype.Numeric     `json:"amount"`
	Status      pgtype.Text        `json:"status"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetInvoiceByID(ctx context.Context, id string) (GetInvoiceByIDRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i GetInvoiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.Amount,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (id, topic, payload, status, created_at) 
VALUES ($1, $2, $3, 'pending', NOW())
`

type InsertOutboxEventParams struct {
	ID      string `json:"id"`
	Topic   string `json:"topic"`
	Payload []byte `json:"payload"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent, arg.ID, arg.Topic, arg.Payload)
	return err
}
