// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type AppointmentsStatus string

const (
	AppointmentsStatusScheduled AppointmentsStatus = "scheduled"
	AppointmentsStatusCompleted AppointmentsStatus = "completed"
	AppointmentsStatusCancelled AppointmentsStatus = "cancelled"
	AppointmentsStatusNoShow    AppointmentsStatus = "no_show"
)

func (e *AppointmentsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentsStatus(s)
	case string:
		*e = AppointmentsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentsStatus: %T", src)
	}
	return nil
}

type NullAppointmentsStatus struct {
	AppointmentsStatus AppointmentsStatus `json:"appointments_status"`
	Valid              bool               `json:"valid"` // Valid is true if AppointmentsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentsStatus), nil
}

type OutboxEventsStatus string

const (
	OutboxEventsStatusPending   OutboxEventsStatus = "pending"
	OutboxEventsStatusProcessed OutboxEventsStatus = "processed"
	OutboxEventsStatusFailed    OutboxEventsStatus = "failed"
)

func (e *OutboxEventsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxEventsStatus(s)
	case string:
		*e = OutboxEventsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxEventsStatus: %T", src)
	}
	return nil
}

type NullOutboxEventsStatus struct {
	OutboxEventsStatus OutboxEventsStatus `json:"outbox_events_status"`
	Valid              bool               `json:"valid"` // Valid is true if OutboxEventsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxEventsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxEventsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxEventsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxEventsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxEventsStatus), nil
}

type Appointment struct {
	ID          string                 `json:"id"`
	PatientID   string                 `json:"patient_id"`
	DoctorID    string                 `json:"doctor_id"`
	ScheduledAt time.Time              `json:"scheduled_at"`
	Status      NullAppointmentsStatus `json:"status"`
	Notes       sql.NullString         `json:"notes"`
	CreatedAt   sql.NullTime           `json:"created_at"`
	UpdatedAt   sql.NullTime           `json:"updated_at"`
}

type OutboxEvent struct {
	ID          string                 `json:"id"`
	Topic       string                 `json:"topic"`
	Payload     json.RawMessage        `json:"payload"`
	Status      NullOutboxEventsStatus `json:"status"`
	Attempts    sql.NullInt32          `json:"attempts"`
	CreatedAt   sql.NullTime           `json:"created_at"`
	ProcessedAt sql.NullTime           `json:"processed_at"`
}
