// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"context"
)

type Querier interface {
	GetAppointmentByID(ctx context.Context, id string) (GetAppointmentByIDRow, error)
	InsertAppointment(ctx context.Context, arg InsertAppointmentParams) error
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
}

var _ Querier = (*Queries)(nil)
