// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package query

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const getAppointmentByID = `-- name: GetAppointmentByID :one
SELECT id, patient_id, doctor_id, scheduled_at, status, created_at 
FROM appointments 
WHERE id = ?
`

type GetAppointmentByIDRow struct {
	ID          string                 `json:"id"`
	PatientID   string                 `json:"patient_id"`
	DoctorID    string                 `json:"doctor_id"`
	ScheduledAt time.Time              `json:"scheduled_at"`
	Status      NullAppointmentsStatus `json:"status"`
	CreatedAt   sql.NullTime           `json:"created_at"`
}

func (q *Queries) GetAppointmentByID(ctx context.Context, id string) (GetAppointmentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAppointmentByID, id)
	var i GetAppointmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.ScheduledAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertAppointment = `-- name: InsertAppointment :exec
INSERT INTO appointments (id, patient_id, doctor_id, scheduled_at, status, created_at) 
VALUES (?, ?, ?, ?, 'scheduled', NOW())
`

type InsertAppointmentParams struct {
	ID          string    `json:"id"`
	PatientID   string    `json:"patient_id"`
	DoctorID    string    `json:"doctor_id"`
	ScheduledAt time.Time `json:"scheduled_at"`
}

func (q *Queries) InsertAppointment(ctx context.Context, arg InsertAppointmentParams) error {
	_, err := q.db.ExecContext(ctx, insertAppointment,
		arg.ID,
		arg.PatientID,
		arg.DoctorID,
		arg.ScheduledAt,
	)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (id, topic, payload, status, created_at) 
VALUES (?, ?, ?, 'pending', NOW())
`

type InsertOutboxEventParams struct {
	ID      string          `json:"id"`
	Topic   string          `json:"topic"`
	Payload json.RawMessage `json:"payload"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.ExecContext(ctx, insertOutboxEvent, arg.ID, arg.Topic, arg.Payload)
	return err
}
